# Generated by Django 5.2.8 on 2025-12-01 14:38

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('matric_number', models.CharField(help_text='Format: 11-digit matric number (e.g., 23010301040)', max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid matric number (11 digits, e.g., 23010301040)', regex='^\\d{11}$')])),
                ('department', models.CharField(choices=[('CSC', 'Computer Science'), ('MCM', 'Mass Communication'), ('NUR', 'Nursing Science'), ('IT', 'Information Technology'), ('EEE', 'Electrical Engineering'), ('MCE', 'Mechanical Engineering'), ('CVE', 'Civil Engineering'), ('CHE', 'Chemical Engineering'), ('MTH', 'Mathematics'), ('PHY', 'Physics'), ('CHM', 'Chemistry'), ('BIO', 'Biology'), ('OTHER', 'Other')], max_length=10)),
                ('level', models.IntegerField(choices=[(100, '100 Level'), (200, '200 Level'), (300, '300 Level'), (400, '400 Level'), (500, '500 Level')], default=100)),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('total_games', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('draws', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=1200)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=8, unique=True)),
                ('fen', models.CharField(default='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1', max_length=100)),
                ('status', models.CharField(choices=[('waiting', 'Waiting for opponent'), ('active', 'Game in progress'), ('completed', 'Game completed'), ('abandoned', 'Game abandoned')], default='waiting', max_length=20)),
                ('white_guest_name', models.CharField(blank=True, max_length=50, null=True)),
                ('black_guest_name', models.CharField(blank=True, max_length=50, null=True)),
                ('time_control', models.CharField(choices=[('bullet_1', '1 min (Bullet)'), ('bullet_2', '2 min (Bullet)'), ('blitz_3', '3 min (Blitz)'), ('blitz_5', '5 min (Blitz)'), ('rapid_10', '10 min (Rapid)'), ('rapid_15', '15 min (Rapid)'), ('classical_30', '30 min (Classical)'), ('unlimited', 'Unlimited')], default='blitz_5', max_length=20)),
                ('is_rated', models.BooleanField(default=True)),
                ('is_private', models.BooleanField(default=False)),
                ('white_time_remaining', models.IntegerField(default=300)),
                ('black_time_remaining', models.IntegerField(default=300)),
                ('last_move_time', models.DateTimeField(blank=True, null=True)),
                ('winner', models.CharField(blank=True, choices=[('white', 'White'), ('black', 'Black'), ('draw', 'Draw')], max_length=10, null=True)),
                ('result_reason', models.CharField(blank=True, choices=[('checkmate', 'Checkmate'), ('resignation', 'Resignation'), ('timeout', 'Time out'), ('stalemate', 'Stalemate'), ('insufficient', 'Insufficient material'), ('agreement', 'Draw by agreement'), ('repetition', 'Threefold repetition'), ('fifty_move', 'Fifty-move rule'), ('abandoned', 'Abandoned')], max_length=50, null=True)),
                ('move_history', models.TextField(blank=True, default='[]')),
                ('move_count', models.IntegerField(default=0)),
                ('captured_pieces', models.TextField(blank=True, default='{"white": [], "black": []}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('black_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_as_black', to=settings.AUTH_USER_MODEL)),
                ('white_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_as_white', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('color', models.CharField(choices=[('white', 'White'), ('black', 'Black')], max_length=5)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_number', models.IntegerField()),
                ('player_color', models.CharField(max_length=5)),
                ('move_san', models.CharField(max_length=10)),
                ('move_from', models.CharField(max_length=2)),
                ('move_to', models.CharField(max_length=2)),
                ('captured_piece', models.CharField(blank=True, max_length=1, null=True)),
                ('fen_after', models.CharField(max_length=100)),
                ('time_spent', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='game.game')),
            ],
            options={
                'ordering': ['move_number'],
            },
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['code'], name='game_game_code_132bf9_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['status', 'created_at'], name='game_game_status_9bfe99_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['white_player', 'created_at'], name='game_game_white_p_38d9a8_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['black_player', 'created_at'], name='game_game_black_p_ae15c8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gamesession',
            unique_together={('session_key', 'game'), ('user', 'game')},
        ),
    ]
