# Generated by Django 5.2.8 on 2025-12-01 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rating_assigned',
            field=models.BooleanField(default=False, help_text='True if rating has been calculated'),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.IntegerField(choices=[(50, 'Foundation'), (100, '100 Level'), (200, '200 Level'), (300, '300 Level'), (400, '400 Level'), (500, '500 Level')], default=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='rating',
            field=models.IntegerField(blank=True, default=None, help_text='ELO rating - assigned after 5 games', null=True),
        ),
    ]
