# Generated by Django 5.2.8 on 2025-12-02 23:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_user_rating_assigned_alter_user_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='timer_last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='achievements',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='current_win_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='longest_win_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='matric_number',
            field=models.CharField(help_text='Format: 11-digit matric number (e.g., 23010301040) or F + 7 digits for Foundation', max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid matric number: 11 digits (e.g., 23010301040) or 1 letter + 7 digits for Foundation (e.g., F2301040)', regex='^(\\d{11}|[A-Z]\\d{7})$')]),
        ),
    ]
