# Generated by Django 5.2.8 on 2025-12-03 22:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_game_timer_last_updated_user_achievements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='matric_number',
            field=models.CharField(help_text='Enter your Matric Number or your Application Number', max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid matric number or Application Number', regex='^(\\d{11}|[A-Z]\\d{7})$')]),
        ),
    ]
